"use client";

import React, { useState, useEffect, use } from "react";
import Link from "next/link";
import { DashboardSidebar } from "@/components/layouts/dashboard-sidebar";
import {
  ArrowLeft, Settings, Download, Share2, Sparkles, ChevronDown, ChevronRight,
  Plus, Bold, Italic, Underline, AlignLeft, AlignCenter, AlignRight, List,
  Image as ImageIcon, Link2, Wand2, Undo, Redo, Check, MoreHorizontal, BookOpen, Loader2
} from "lucide-react";

export default function EditorPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const [book, setBook] = useState<any>(null);
  const [chapters, setChapters] = useState<any[]>([]);
  const [activeChapterId, setActiveChapterId] = useState<number>(1);
  const [content, setContent] = useState<string>("");
  const [showAIPanel, setShowAIPanel] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [aiLoading, setAiLoading] = useState(false);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    try {
      // 1. Try reading bookloom_current_book
      const currentStr = localStorage.getItem("bookloom_current_book");
      let foundBook: any = null;
      if (currentStr) {
        const parsed = JSON.parse(currentStr);
        if (parsed && (parsed.id === resolvedParams.id || resolvedParams.id === "1")) {
          foundBook = parsed;
        }
      }

      // 2. Try looking in bookloom_books array
      if (!foundBook) {
        const booksStr = localStorage.getItem("bookloom_books");
        if (booksStr) {
          const list = JSON.parse(booksStr);
          foundBook = list.find((b: any) => b.id === resolvedParams.id) || list[0];
        }
      }

      if (foundBook) {
        setBook(foundBook);
        if (Array.isArray(foundBook.chapters) && foundBook.chapters.length > 0) {
          setChapters(foundBook.chapters);
          setActiveChapterId(foundBook.chapters[0].id || 1);
          setContent(foundBook.chapters[0].content || "");
          return;
        }
      }
    } catch (e) {}

    // Fallback default chapters if none loaded
    const fallbackChapters = [
      { id: 1, chapterNumber: 1, title: "Chapter 1: The Mindset Shift", content: "# Chapter 1: The Mindset Shift\n\nSuccess in wealth-building begins not with a paycheck, but with a perspective. The difference between those who consistently build wealth and those who struggle is rarely a matter of intelligence—it's almost always about mindset.\n\n## Core Principles\n\n- **Belief in value creation**: Wealth is generated by solving high-impact problems.\n- **Long-term leverage**: Compounding works exponentially across time.", status: "complete" },
      { id: 2, chapterNumber: 2, title: "Chapter 2: Strategic Blueprint", content: "# Chapter 2: Strategic Blueprint\n\nDesigning execution frameworks for enterprise scaling.", status: "complete" },
    ];
    setChapters(fallbackChapters);
    setActiveChapterId(1);
    setContent(fallbackChapters[0].content);
  }, [resolvedParams.id]);

  const handleSelectChapter = (ch: any) => {
    setActiveChapterId(ch.id);
    setContent(ch.content || `# ${ch.title}\n\nChapter manuscript content...`);
  };

  const handleContentChange = (newText: string) => {
    setContent(newText);
    setChapters(prev => prev.map(c => c.id === activeChapterId ? { ...c, content: newText } : c));
  };

  const handleAIGenerateText = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    try {
      const activeCh = chapters.find(c => c.id === activeChapterId);
      const res = await fetch("/api/generate-chapter", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          bookTitle: book?.title || "BookLoom Ebook",
          chapterNumber: activeCh?.chapterNumber || activeChapterId,
          totalChapters: chapters.length,
          title: activeCh?.title || "Custom Section",
          summary: aiPrompt,
          prompt: aiPrompt,
        }),
      });

      const json = await res.json();
      if (json.success && json.data?.content) {
        const appended = content + "\n\n" + json.data.content;
        handleContentChange(appended);
        setAiPrompt("");
      } else {
        alert(json.error || "AI Generation failed");
      }
    } catch (err: any) {
      alert("AI Assistant error: " + err.message);
    } finally {
      setAiLoading(false);
    }
  };

  const handleAIGenerateImage = async () => {
    setAiLoading(true);
    try {
      const activeCh = chapters.find(c => c.id === activeChapterId);
      const promptToUse = aiPrompt.trim() || `High quality aesthetic ebook illustration for chapter: ${activeCh?.title || "Book Section"}`;
      
      const res = await fetch("/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: promptToUse, width: 1024, height: 768 }),
      });

      const json = await res.json();
      if (json.success && json.imageUrl) {
        const markdownImg = `\n\n![${promptToUse}](${json.imageUrl})\n*Illustration: ${promptToUse}*\n\n`;
        const appended = content + markdownImg;
        handleContentChange(appended);
        setAiPrompt("");
      } else {
        alert(json.error || "Image generation failed");
      }
    } catch (err: any) {
      alert("Image Assistant error: " + err.message);
    } finally {
      setAiLoading(false);
    }
  };

  const handleExportBook = async (format: "PDF" | "EPUB" | "TXT" | "HTML" = "PDF") => {
    setExporting(true);
    try {
      const manuscriptBody = chapters.map(c => `${c.title}\n\n${c.content}`).join("\n\n---\n\n");
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ebookId: book?.id || resolvedParams.id,
          title: book?.title || "BookLoom_Ebook",
          format,
          content: manuscriptBody,
        }),
      });
      const json = await res.json();
      if (json.success && json.export?.downloadUrl) {
        const a = document.createElement("a");
        a.href = json.export.downloadUrl;
        a.download = json.export.filename || `ebook.${format.toLowerCase()}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      } else {
        alert("Export failed: " + (json.error || "Unknown error"));
      }
    } catch (e: any) {
      alert("Export error: " + e.message);
    } finally {
      setExporting(false);
    }
  };

  const currentBookTitle = book?.title || "The Wealth Mindset";
  const currentTotalWords = chapters.reduce((acc, curr) => acc + (curr.content ? curr.content.split(/\s+/).length : 0), 0);

  return (
    <div style={{ display: "flex", height: "100vh", background: "#F8F5F0", fontFamily: "Inter, sans-serif", overflow: "hidden" }}>
      {/* Sidebar */}
      <DashboardSidebar />

      {/* Left panel - Chapter list */}
      <div style={{ width: 240, background: "#FFFFFF", borderRight: "1px solid #E8E4DF", display: "flex", flexDirection: "column", overflow: "hidden" }}>
        <div style={{ padding: "16px", borderBottom: "1px solid #E8E4DF" }}>
          <Link href="/dashboard/library" style={{ display: "flex", alignItems: "center", gap: 8, color: "#4A4A4A", textDecoration: "none", fontSize: 13, marginBottom: 12 }}>
            <ArrowLeft size={14} /> Back to Library
          </Link>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ width: 34, height: 44, borderRadius: 4, background: "#1A1A1A", display: "flex", alignItems: "center", justifyContent: "center", color: "#C49A3C", fontWeight: 700, fontSize: 12, flexShrink: 0 }}>
              📖
            </div>
            <div style={{ overflow: "hidden" }}>
              <div style={{ fontWeight: 700, fontSize: 13, color: "#1A1A1A", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                {currentBookTitle}
              </div>
              <div style={{ fontSize: 11, color: "#9A9A9A" }}>{chapters.length} Chapters · AI Draft</div>
            </div>
          </div>
        </div>

        <div style={{ flex: 1, overflowY: "auto", padding: "12px 8px" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 8px", marginBottom: 8 }}>
            <span style={{ fontSize: 11, fontWeight: 600, color: "#9A9A9A", textTransform: "uppercase", letterSpacing: "0.05em" }}>Chapters</span>
            <button
              onClick={() => {
                const newCh = { id: Date.now(), chapterNumber: chapters.length + 1, title: `Chapter ${chapters.length + 1}`, content: `# Chapter ${chapters.length + 1}\n\nNew manuscript chapter...`, status: "complete" };
                setChapters([...chapters, newCh]);
                handleSelectChapter(newCh);
              }}
              style={{ background: "none", border: "none", cursor: "pointer", color: "#C49A3C", display: "flex", alignItems: "center", gap: 4, fontSize: 12, fontWeight: 600 }}>
              <Plus size={12} /> Add
            </button>
          </div>
          {chapters.map((ch) => (
            <button key={ch.id} onClick={() => handleSelectChapter(ch)}
              style={{
                width: "100%", display: "flex", alignItems: "center", gap: 8, padding: "9px 10px",
                borderRadius: 8, border: "none", background: activeChapterId === ch.id ? "#1A1A1A" : "transparent",
                cursor: "pointer", textAlign: "left", marginBottom: 2, fontFamily: "Inter, sans-serif"
              }}>
              <div style={{ width: 18, height: 18, borderRadius: 4, border: `1.5px solid ${activeChapterId === ch.id ? "#FFFFFF" : "#22C55E"}`, background: "#22C55E", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <Check size={10} color="#FFFFFF" />
              </div>
              <span style={{ fontSize: 12, fontWeight: activeChapterId === ch.id ? 600 : 400, color: activeChapterId === ch.id ? "#FFFFFF" : "#4A4A4A", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                {ch.title}
              </span>
            </button>
          ))}
        </div>

        {/* Word Count */}
        <div style={{ padding: 16, borderTop: "1px solid #E8E4DF" }}>
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, color: "#4A4A4A", marginBottom: 6 }}>
            <span>Manuscript Words</span>
            <span style={{ fontWeight: 700, color: "#C49A3C" }}>{currentTotalWords.toLocaleString()} Words</span>
          </div>
          <div style={{ height: 6, background: "#F0EDE8", borderRadius: 999 }}>
            <div style={{ width: "100%", height: "100%", background: "#C49A3C", borderRadius: 999 }} />
          </div>
        </div>
      </div>

      {/* Main Editor */}
      <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
        {/* Top bar */}
        <div style={{ background: "#FFFFFF", borderBottom: "1px solid #E8E4DF", padding: "0 20px", height: 52, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
            {[
              { icon: <Bold size={14} />, label: "Bold" },
              { icon: <Italic size={14} />, label: "Italic" },
              { icon: <Underline size={14} />, label: "Underline" },
            ].map((b) => (
              <button key={b.label} title={b.label} style={{ padding: "6px", border: "1px solid #E8E4DF", borderRadius: 6, background: "transparent", cursor: "pointer", color: "#4A4A4A", display: "flex", alignItems: "center" }}>
                {b.icon}
              </button>
            ))}
            <div style={{ width: 1, height: 24, background: "#E8E4DF" }} />
            {[
              { icon: <AlignLeft size={14} /> },
              { icon: <AlignCenter size={14} /> },
              { icon: <AlignRight size={14} /> },
            ].map((b, i) => (
              <button key={i} style={{ padding: "6px", border: "1px solid #E8E4DF", borderRadius: 6, background: i === 0 ? "#F0EDE8" : "transparent", cursor: "pointer", color: "#4A4A4A", display: "flex", alignItems: "center" }}>
                {b.icon}
              </button>
            ))}
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <button
              onClick={() => setShowAIPanel(!showAIPanel)}
              style={{ display: "flex", alignItems: "center", gap: 6, padding: "8px 14px", background: "#FBF3E0", border: "1px solid #EFD98A", borderRadius: 8, cursor: "pointer", fontSize: 13, fontWeight: 600, color: "#9A6F1A", fontFamily: "Inter, sans-serif" }}>
              <Sparkles size={14} /> AI Writer
            </button>
            <button
              onClick={() => handleExportBook("PDF")}
              disabled={exporting}
              style={{ display: "flex", alignItems: "center", gap: 6, padding: "8px 14px", background: "#1A1A1A", border: "none", borderRadius: 8, cursor: exporting ? "not-allowed" : "pointer", fontSize: 13, fontWeight: 600, color: "#FFFFFF", fontFamily: "Inter, sans-serif" }}>
              {exporting ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />} Download PDF
            </button>
          </div>
        </div>

        {/* Editor Area */}
        <div style={{ flex: 1, display: "flex", overflow: "hidden" }}>
          {/* Writing area */}
          <div style={{ flex: 1, padding: "32px 48px", overflowY: "auto", background: "#F8F5F0" }}>
            <div style={{ maxWidth: 720, margin: "0 auto", background: "#FFFFFF", borderRadius: 12, border: "1px solid #E8E4DF", padding: "48px 56px", boxShadow: "0 4px 16px rgba(0,0,0,0.04)", minHeight: 650 }}>
              <textarea
                value={content}
                onChange={e => handleContentChange(e.target.value)}
                placeholder="Write your manuscript here..."
                style={{
                  width: "100%", minHeight: 550, border: "none", outline: "none", resize: "none",
                  fontFamily: "'Playfair Display', Georgia, serif",
                  fontSize: 16, lineHeight: 1.8, color: "#1A1A1A", background: "transparent"
                }}
              />
            </div>
          </div>

          {/* Right AI panel */}
          {showAIPanel && (
            <div style={{ width: 300, background: "#FFFFFF", borderLeft: "1px solid #E8E4DF", display: "flex", flexDirection: "column" }}>
              <div style={{ padding: 16, borderBottom: "1px solid #E8E4DF" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 12 }}>
                  <Sparkles size={14} color="#C49A3C" />
                  <span style={{ fontWeight: 700, fontSize: 14, color: "#1A1A1A" }}>AI Writing Assistant</span>
                </div>
                <textarea
                  value={aiPrompt}
                  onChange={e => setAiPrompt(e.target.value)}
                  placeholder="Describe what to add, expand, or write next in this chapter..."
                  style={{ width: "100%", height: 90, border: "1px solid #E8E4DF", borderRadius: 8, padding: 10, fontSize: 12, resize: "none", fontFamily: "Inter, sans-serif", outline: "none", boxSizing: "border-box" }}
                />
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginTop: 8 }}>
                  <button
                    onClick={handleAIGenerateText}
                    disabled={aiLoading || !aiPrompt.trim()}
                    style={{ background: "#1A1A1A", color: "#FFFFFF", border: "none", borderRadius: 8, padding: "10px 8px", fontSize: 11, fontWeight: 600, cursor: aiLoading ? "not-allowed" : "pointer", fontFamily: "Inter, sans-serif", display: "flex", alignItems: "center", justifyContent: "center", gap: 4 }}>
                    {aiLoading ? <Loader2 size={12} className="animate-spin" /> : <Wand2 size={12} />}
                    AI Text
                  </button>
                  <button
                    onClick={handleAIGenerateImage}
                    disabled={aiLoading}
                    style={{ background: "#C49A3C", color: "#FFFFFF", border: "none", borderRadius: 8, padding: "10px 8px", fontSize: 11, fontWeight: 600, cursor: aiLoading ? "not-allowed" : "pointer", fontFamily: "Inter, sans-serif", display: "flex", alignItems: "center", justifyContent: "center", gap: 4 }}>
                    {aiLoading ? <Loader2 size={12} className="animate-spin" /> : <ImageIcon size={12} />}
                    AI Picture
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

